export const SEED_TENANTS = [
  'Locos Bet',
  'Casino Premium',
  'casino en casa',
  'DoradoBet',
  'EstelarBet',
  'BetCrush',
  'Apuesta City',
  'Ganalucas',
  'Betano',
  'Cristian Farias',
  'Casinonfire',
  'Betsala',
  'CLEO',
  'Juega Con Chama',
  '20bet',
  'Casino Super Match',
  'JumpCasinos',
  'Gran Astro VIP',
  'National Casino',
  'Bizzo',
  'Juegaqui',
  'PKBets',
  'Novibet',
  'SELEKTO',
  'Juegatela',
  'Jazz Gaming',
  'GanaConRoma',
  'CasinoModelo',
  'MCV',
  'Xkalibur',
  'BETLUCAS',
  'JuegaConHorus',
  'Azares',
  'Ajugar.bet',
  'MAXIMA FORTUNA',
  'BetChile365',
  'Yogano',
  'Tucasinoencasa',
  'MediPass',
  'remesas365',
  'Star Poker',
  'LuckyBlack',
  'Privilegewin',
  'Starbig',
  'Golden Money',
  'Olimpos',
  'MiMillon',
  'Casino Estelar',
  'GranaWin',
  'PAY EASY',
  'Juega en Línea',
  'Chama Casinos',
  'Coolbet Operaciones',
  'Latribet',
  'Jugabet',
  'BETANO',
  'PlatinoStar',
  'Kappbet',
  'Jugabet EC',
  'LaRocaBet',
  'OKTO',
  'Monetix',
  'ChileC',
  'MilloBet',
  'Coolbet',
  'PLAYGREEN',
  'AstroBet',
  'JEL',
  'Jugabet CL',
  'Juego Experto',
  'FORBET S.C.',
  'AtacamaBet',
  'MSV',
  'Beterix',
  'Totalbet',
  '1Xbet',
  'Layla',
  'Fun88',
  'PowerBet',
  'PlaySala',
  'BacanBet',
  'Playuzu',
  'ApuesteReal',
  '1WIN',
  'Playuzu CL',
  'Dreams Latam',
  'Bet4',
  'Coolbet CL',
  'Bet7K',
  'Betcore EC',
  'Logistica Naviera',
  'Mas1x2',
  'Millobet CL',
  'Topacio',
  'More Payments',
  'Punchbet',
  'Betsson Chile',
  'BETROIA GAMING',
  'Beton',
  'RushBet',
  'Brazino777 CL',
  'BONUM',
  'LUANCO',
  'BetanDel'
];
